language: node_js

node_js:
  - '6'

sudo: false

cache:
  apt: true
  directories:
    - node_modules

addons:
  ssh_known_hosts: github.com

before_script:
- export TZ='Asia/Shanghai'

script:
  - npm run build

deploy:
  provider: script
  script: '.travis/deploy.sh'
  skip_cleanup: true
  on:
    branch: source
