title: I sudo X
subtitle:
description:
author: sudoz
avatar: https://avatars1.githubusercontent.com/u/8557100?v=3&u=3271f83b84ff18d515f17afa931059ef4d88a267&s=400
language: zh-Hans
timezone: Asia/Shanghai

url: https://isudox.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: README.md

new_post_name: :year-:month-:day-:title.md # File name of new posts
auto_spacing: true
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true

highlight:
  enable: true
  backtick_code_block: true
  line_number: true
  auto_detect: false
  tab_replace: '  '

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# record count
index_generator:
  per_page: 10

archive_generator:
  per_page: 10
  yearly: true
  monthly: true

tag_generator:
  per_page: 10

theme: zext

deploy:
  type: git
  repo: git@github.com:isudox/isudox.github.io.git
  branch: master
  # repo:
  #   github: git@github.com:isudox/isudox.github.io.git,master
  #   gitvps: git@45.33.47.109:isudox.github.io.git,master

social:
  Github: https://github.com/isudox
  # Twitter: https://twitter.com/isudox
  StackOverflow: http://stackoverflow.com/users/4305743/sudoz
  # LeetCode: https://leetcode.com/sudoz/
  # Douban: http://www.douban.com/people/83781615
  # weibo: http://weibo.com/your-user-name
  # zhihu: http://www.zhihu.com/people/your-user-name

disqus_shortname: isudox
jiathis: false
swiftype_key: bDJ1BXjgkwVZSrnkzynx
google_analytics: UA-67443010-1
baidu_analytics: 416f859610dfc2db62c90f5d33de2fdd
# duoshuo_shortname: isudox
