# internal settings
baseURL: "https://isudox.com/"
params:
  author: "isudox"
  description: "My personal blog site."
  startYear: 2015
  toc: true
languageCode: "zh"
title: "I sudo X"
theme: "nova"
uglyurls: "false"
permalinks:
  posts: "/:year/:month/:day/:filename/"
paginate: 10
hasCJKLanguage: true
defaultContentLanguage: "zh"
taxonomies:
  category: categories
  tag: tags
disablePathToLower: true
menu:
  main:
  - identifier: archive
    name: archive
    pre: <i class='fa fa-heart'></i>
    url: /posts/
    weight: 1
  - identifier: tag
    name: tag
    pre: <i class='fa fa-heart'></i>
    url: /tags/
    weight: 2
  - identifier: about
    name: About
    pre: <i class='fa fa-heart'></i>
    url: /about/
    weight: 10
privacy:
  disqus:
    disable: false
  googleAnalytics:
    anonymizeIP: false
    disable: false
    respectDoNotTrack: false
    useSessionStorage: false
  instagram:
    disable: false
    simple: false
  twitter:
    disable: false
    enableDNT: false
    simple: false
  vimeo:
    disable: false
    simple: false
  youtube:
    disable: false
    privacyEnhanced: false

# custom settings
disqusShortname: "isudox"

# https://gohugo.io/getting-started/configuration-markup
markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: no
    lineNumbersInTable: false
    noClasses: true
    style: solarized-light
    tabWidth: 4
  goldmark:
    renderer:
      unsafe: true
